### ISSUE TITLE
Import error with numpy 1.16

### ISSUE THREAD

**Issue by ml31415** [scipy/weave#11]
```
>>> from weave import inline
ImportError: cannot import name _get_ndarray_c_version
```

Not much to add. Looks like numpy changed some internals, and weave would need to be updated for that.

**Comment by ilayn** [comment]
I am not sure if anybody would work on `weave` for newer NumPy versions though technically we should still support this last NumPy version since Python2 support is removed from NumPy >=v1.17.

However this would probably depend mostly on the volunteer effort.

**Comment by rgommers** [comment]
Probably a good idea to fix indeed. I'm happy to cut a new release in February. A PR with a fix would help though.

**Comment by mdepitta** [comment]
Hello folks, any update on this? I keep getting the same error even downgrading to numpy 1.15, and I desperately needs to use weave. What was the workaround eventually?

**Comment by ilayn** [comment]
The immediate fix is to get the master branch. Otherwise in a week or two @rgommers will roll out a new version 0.17 See #12 

The long solution is to stop using Python 2 and switch to Cython since this will be the last release.

**Comment by rgommers** [comment]
Okay, a new version with the fix is up on PyPI.
