### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by ahnitz** [scipy/weave#8]
HI All,

I'd like to ask if there is a plan to make a release based on the current version. I'm currently maintaining a library (pycbc) that makes use of weave to speed up parts of the filtering code. We'd like to be able to move to newer versions of scipy, where weave has been removed, but the latest release of weave on pypi is not compatible with this as it still depends on scipy.lib.six. There has been a patch onto this repository to fix this, but there hasn't been an updated release in a couple years. Any idea if this is possible or what the hold ups might be to do a point release with the current version? I apologize if this is something that has already been discussed.

**Comment by rgommers** [comment]
Thanks for asking @ahnitz. No one had any plans for a new release, but then again no one realizes this is a current blocker for people to upgrade scipy.

A new release sounds good, and is not much work.

**Comment by rgommers** [comment]
I sent a message to the scipy-dev mailing list about this. 

Will try to get this done within a week or two. Please feel free to ping me if it takes longer.

**Comment by rgommers** [comment]
v0.16.0 tagged and up on PyPI: https://pypi.python.org/pypi/weave/0.16.0

Sorry about the year-long delay

**Comment by ahnitz** [comment]
@rgommers Thank you! I'll update our codes to use this version.
